import type { Skill } from "./types";


export const SKILLS = {
    "python": { title: "Python", icon: "python" },
    "react": { title: "React", icon: "react" },
    "typescript": { title: "TypeScript", icon: "typescript" },
    "solidity": { title: "Solidity", icon: "solidity" },
    "tailwind": { title: "Tailwind", icon: "tailwind" },
    "postgresql": { title: "PostgreSQL", icon: "postgresql" },
    "graphql": { title: "GraphQL", icon: "graphql" },
    "chromadb": { title: "ChromaDB", icon: "chromadb" },
    "vite": { title: "Vite", icon: "vite" },
    "nextjs": { title: "Next.js", icon: "nextjs", color: "black" },
    "hardhat": { title: "Hardhat", icon: "hardhat" },
    "pytorch": { title: "Pytorch", icon: "pytorch" },
    "fastapi": { title: "FastAPI", icon: "fastapi" },
    "huggingface": { title: "HuggingFace", icon: "huggingface" },
    "docker": { title: "Docker", icon: "docker" },
    "java": { title: "Java", icon: "java" },
    "kotlin": { title: "Kotlin", icon: "kotlin" },
    "spring": { title: "Spring", icon: "spring" },
    "jenkins": { title: "Jenkins", icon: "jenkins" },
    "mongodb": { title: "MondoDB", icon: "mongodb" },
    "github-actions": { title: "GitHub Actions", icon: "github-actions" },
    "kubernetes": { title: "Kubernetes", icon: "kubernetes" },
    "cpp": { title: "C++", icon: "cpp" },
    "rust": { title: "Rust", icon: "rust" },
    "haskell": { title: "Haskell", icon: "haskell" },
    "ocaml": { title: "OCaml", icon: "ocaml" },
    "sql": { title: "SQL", icon: "postgresql" },
    "django": { title: "Django", icon: "django" },
    "astro": { title: "Astro", icon: "astro" },
    "numpy": { title: "Numpy", icon: "numpy" },
    "pandas": { title: "Pandas", icon: "pandas" },
    "sklearn": { title: "Sklearn", icon: "sklearn" },
    "git": { title: "Git", icon: "git" },
    "nixos": { title: "NixOS", icon: "nixos" },
    "arch": { title: "Arch", icon: "arch" },
  } as const satisfies Dictionary<Skill>;